# Generated by Django 4.2.27 on 2026-02-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ünvanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Abunə tarixi')),
            ],
            options={
                'verbose_name': 'Abunəçi',
                'verbose_name_plural': 'Abunəçilər',
                'ordering': ['-created_at'],
            },
        ),
    ]
