# Generated by Django 3.2 on 2026-03-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Kateqoriya adı')),
                ('icon_class', models.CharField(blank=True, default='', help_text='Font Awesome class, məs: fas fa-home', max_length=128, verbose_name='İkon (CSS class)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('coming_soon', models.BooleanField(default=False, help_text="Aktiv edildikdə alt xidmətlər əvəzinə 'Tezliklə' yazısı göstərilir", verbose_name='Tezliklə')),
            ],
            options={
                'verbose_name': 'Xidmət Kateqoriyası',
                'verbose_name_plural': 'Xidmət Kateqoriyaları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Xidmət adı')),
                ('url', models.CharField(blank=True, default='', help_text='Boş buraxsanız xidmətlər səhifəsinə yönləndirilir', max_length=512, verbose_name='Link (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.servicecategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['order'],
            },
        ),
    ]
