# Generated by Django 3.2 on 2026-03-12 09:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_servicecategory_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Detal səhifəsinin başlıq hissəsi üçün', null=True, upload_to='services/banners/', verbose_name='Banner şəkli'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Detal səhifəsində görünəcək', verbose_name='Ətraflı təsvir'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Əsas şəkil'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Xidmətlər səhifəsində kartda görünəcək', verbose_name='Qısa təsvir'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=256, verbose_name='Slug (URL)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='icon_class',
            field=models.CharField(blank=True, default='', help_text='Font Awesome class, məs: fas fa-wrench', max_length=128, verbose_name='İkon (CSS class)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Qısa təsvir'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='url',
            field=models.CharField(blank=True, default='', help_text='Boş buraxsanız kateqoriya detal səhifəsinə yönləndirilir', max_length=512, verbose_name='Link (URL)'),
        ),
    ]
