# Generated by Django 3.2 on 2026-03-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_detail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
